### ISSUE TITLE
"can't find gem terraform_landscape"

### ISSUE THREAD

**Issue by WurmD** [coinbase/terraform-landscape#133]
```
$ terraform -version
Terraform v1.5.7
on linux_amd64
+ provider registry.terraform.io/newrelic/newrelic v3.27.1

$ ruby --version
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]

$ terraform plan -lock=false | landscape
Traceback (most recent call last):
        2: from /usr/local/bin/landscape:23:in `<main>'
        1: from /usr/lib/ruby/2.5.0/rubygems.rb:308:in `activate_bin_path'
/usr/lib/ruby/2.5.0/rubygems.rb:289:in `find_spec_for_exe': can't find gem terraform_landscape (>= 0.a) with executable landscape (Gem::GemNotFoundException)
```

**Note:**
```
$ sudo gem install terraform_landscape
...

$ terraform plan -lock=false | landscape
-bash: /usr/local/bin/landscape: Permission denied
```
so I did
```
$ sudo chmod 755 /usr/local/bin/landscape*
```

**Comment by Danielkozicki24** [comment]
Ok
